### ISSUE TITLE
Tratamento de entrada

### ISSUE THREAD

**Issue by agramarques** [agramarques/ProjetoPLP#1]
Falta fazer um tratamento de entrada nos comandos, ou seja, o default quando o comando passado não tiver em uma das listas de comandos aceitos. Decidir o que fazer, pode ser simplesmente retornar a pilha inalterada, ou dar um aviso antes e retornar a pilha.

**Comment by filipepiresg** [comment]
Já fiz esse tratamento! Ao passar um comando que não está em nenhuma das listas, ele simplesmente retorna a lista inalterada.
