### ISSUE TITLE
clear stack

### ISSUE THREAD

**Issue by agramarques** [agramarques/ProjetoPLP#5]
Ainda falta fazer o método pra limpar a pilha. Talvez deva mudar o if-else de calc para uma estrutura múltipla, pra tratar mais casos, além de somente o "quit", acho que o "help" e o "clear" poderiam ser tratados já em calc, em vez de passar para oper.

**Comment by filipepiresg** [comment]
Também acho, mas estava pensando em colocar esses 3 comandos, ou quem sabe ate mais, no mais do Calc.hs
